### ISSUE TITLE
Feature request: Duplicate artboards

### ISSUE THREAD

**Issue by Arkkimaagi** [turbobabr/duplicator#1]
This seems like an obvious next step. It was the first thing I tried to do with the plugin. :)

Is this feature planned or is there something missing from Sketch that's needed to get this going?

**Comment by turbobabr** [comment]
Thanks for the suggestion! I'm suffering without it as well. We'll definitely implement it pretty soon.

**Comment by turbobabr** [comment]
It's been a long time... it's finally here! :)
