### ISSUE TITLE
Plugin not working Sketch v3.8.1

### ISSUE THREAD

**Issue by jord0** [turbobabr/duplicator#10]
Very sad. Noticing this in the the latest public release today.

**Comment by pixelyze** [comment]
I confirm... very sad like you say

**Comment by ghost** [comment]
will there be an update?

**Comment by morecrazyang** [comment]
是的，3.8以后就不能工作了，捉急！～

**Comment by HansonChan** [comment]
`
16/5/23 13:44:42.300 Sketch[4358]: Exception: TypeError: doc.actionsController().actionWithName is not a function. (In 'doc.actionsController().actionWithName("MSCanvasActions")', 'doc.actionsController().actionWithName' is undefined)
`

**Comment by penerwang** [comment]
not work

**Comment by morecrazyang** [comment]
@HansonChan 这段代码怎么用？复制在哪里替换吗？

**Comment by turbobabr** [comment]
Hey Guys!

New version of Duplicator with 3.8 support is available:
https://github.com/turbobabr/duplicator/archive/duplicator-v1.1.zip

**Comment by penerwang** [comment]
@morecrazyang 删除旧版插件，下载新版插件。

**Comment by HansonChan** [comment]
@morecrazyang what i posted was debug logs.
