### ISSUE TITLE
插件侠！～快快出现！～大家都在等你

### ISSUE THREAD

**Issue by morecrazyang** [turbobabr/duplicator#11]
插件侠！～快快出现！～大家都在等你插件侠！～快快出现！～大家都在等你插件侠！～快快出现！～大家都在等你插件侠！～快快出现！～大家都在等你

**Comment by turbobabr** [comment]
New version of Duplicator with 3.8 support is available:
https://github.com/turbobabr/duplicator/archive/duplicator-v1.1.zip
