### ISSUE TITLE
The plugin has stop working in sketch 43 (38999)

### ISSUE THREAD

**Issue by ddelaiglesia** [turbobabr/duplicator#12]

**Comment by longzheng** [comment]
+1

**Comment by robinrowell** [comment]
Sketch 43 (39012)

+1

UI is showing as normal for menu selections and for the step and repeat dialog box, but the commands no longer have any effect.

**Comment by Stetsenko-Igor** [comment]
Sketch 43.1 (39012)
Yup, the same issue, didn't work. Plz fix this usable tool ;)

**Comment by quelion** [comment]
+1

**Comment by ttmouse** [comment]
+1

**Comment by pixelyze** [comment]
+1 Update please :(

**Comment by rafaviana** [comment]
+1

**Comment by peiledoir** [comment]
There had been issues previously when Skype was open, but the current issues don't seem to be related. Maybe another app is interfering? Have not found anything so far.

**Comment by serifluous** [comment]
+1 😢

**Comment by djwgen** [comment]
+1

**Comment by HansonChan** [comment]
Exception: TypeError: undefined is not an object (evaluating 'action.duplicate')

**Comment by RaffeYang** [comment]
+1

**Comment by RaffeYang** [comment]
Use [Looper](https://github.com/sureskumar/Looper) instead.

**Comment by JesseBilsten** [comment]
Created a PR with the plugin now updated to work in Sketch 43.2

- Link: https://github.com/turbobabr/duplicator/pull/14

Let me know if there's any issues and I'll see what I can do to fix.

**Comment by JesseBilsten** [comment]
Can this be closed now?

**Comment by turbobabr** [comment]
@JesseBilsten Sure! Thanks again for the fixes! 🙏
