### ISSUE TITLE
Tabbing on the dialog does not work

### ISSUE THREAD

**Issue by miguelsolorio-zz** [turbobabr/duplicator#13]
When you initiate the dialog, hitting tab does not allow you to move to next field to change the Vertical Spacing. That's a problem for keyboard accessibility, especially for power users.

![image](https://cloud.githubusercontent.com/assets/1030624/24765452/b39f981e-1aac-11e7-90d0-ef9b0ed7b8bd.png)

**Comment by turbobabr** [comment]
Fixed in v2.0
