### ISSUE TITLE
Can't select a duplicated folder

### ISSUE THREAD

**Issue by ivancucer** [turbobabr/duplicator#18]
Hey @turbobabr 👋

macOS 10.12.6 👌
Sketch 46.2 🤤
Duplicator 2.0.0 👍

I can't select any duplicated folders if they are located in subfolders 😮

Take a look at the video proof https://monosnap.com/file/S5K81YzXGOGaFSmofnNfWLoEBonHKJ 🤓

Thank you in advance 👏

Best!
Ivan

**Comment by turbobabr** [comment]
Wow! That's weird... will check it asap! Thanks for reporting!

**Comment by ivancucer** [comment]
@turbobabr any news ? 🤤

**Comment by turbobabr** [comment]
Fixed in 2.0.1 - update should be available via Sketch's auto-update system :)
