### ISSUE TITLE
Support for Sketch 47

### ISSUE THREAD

**Issue by maxvoltar** [turbobabr/duplicator#19]
Currently duplicator isn't working on Sketch 47.

**Comment by turbobabr** [comment]
Hmm.. that's weird. It works for me on 47.1 without any problems. Are you sure you're using the latest version of the plugin?

**Comment by maxvoltar** [comment]
I'm on 2.0.1. Tried reinstalling it, doesn't do anything. Let me know if there's anything I can do to debug :)

**Comment by turbobabr** [comment]
Probably you have an old version of the plugin installed along with the new one. The plugin's bundle name had changed in v2. Also, try to run commands from menu instead of shortcuts - it's possible that some other plugin blocks the shortcuts.

**Comment by maxvoltar** [comment]
Uninstalled the plugin from Finder, reinstalled it, same result. Tried triggering the commands from the menu which doesn't do anything.

**Comment by turbobabr** [comment]
Hmm.. could you check console output?

**Comment by turbobabr** [comment]
Or better DM me via twitter ([@turbobabr](https://twitter.com/turbobabr)) if you have time to help me debugging this thing. Looks like it's something subtle and happens only on your machine. 🤔
