### ISSUE TITLE
Duplications are offset

### ISSUE THREAD

**Issue by jord0** [turbobabr/duplicator#2]
Hi! I'm noticing that Duplicator offsets 10px to the right when I use it to dupe downward (and offsets 10px down when I dupe to the left, etc. for each direction). Have you seen this issue before?

**Comment by jord0** [comment]
This is a screengrab of using the keyboard shortcuts for Duplicate Below and Duplicate Right.
![image](https://cloud.githubusercontent.com/assets/3137659/4597765/9933c77e-50b1-11e4-9707-a0179cbbda12.png)

**Comment by turbobabr** [comment]
Hi! Could you please check this options in your preferences panel?

![rectangle 2](https://cloud.githubusercontent.com/assets/6356526/4597777/bd3bf8c6-50b1-11e4-8fc3-88815c9d64f2.png)

**Comment by jord0** [comment]
You are a GENIUS!!!! Thanks! New favorite plugin!

On Fri, Oct 10, 2014 at 12:15 PM, Andrey Shakhmin notifications@github.com
wrote:

> Hi! Could you please check this options in your preferences panel?
> 
> [image: rectangle 2]
> https://cloud.githubusercontent.com/assets/6356526/4597777/bd3bf8c6-50b1-11e4-8fc3-88815c9d64f2.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/turbobabr/duplicator/issues/2#issuecomment-58703243.

## 

••••••••••••••••••••
_Jordan Presnick_
experience design
www.jordanpresnick.com
san francisco, california

**Comment by turbobabr** [comment]
Not a genius actually.. )) It's just a bug, will fix it pretty soon! :)

**Comment by turbobabr** [comment]
Fixed in v2.0
