### ISSUE TITLE
Support for Sketch 53

### ISSUE THREAD

**Issue by ivancucer** [turbobabr/duplicator#22]
Hi @turbobabr,

Please don't forget to add support for Sketch 53

Best!
Ivan

**Comment by avkvirtru** [comment]
Yes, please. Neither duplicate nor repeat commands work for me. I tried both the default keyboard shortcuts and the Plugin menu items. Hope it's not too much work to fix.

**Comment by turbobabr** [comment]
Done! 🙌 Please update to the latest version

**Comment by avkvirtru** [comment]
@turbobabr thanks very much, back in the duplicating business!
