### ISSUE TITLE
Return way how to duplicate, please

### ISSUE THREAD

**Issue by Zolotarskyi** [turbobabr/duplicator#23]
Before i can select object and duplicate it in any direction many times. Now i stack in one place. Only "cross" duplicates. Because selected only first object, not last duplicated. Hope you understand me. Return please how it works before.

**Comment by turbobabr** [comment]
Sorry for the late replay, what version of Sketch do you use?

**Comment by Zolotarskyi** [comment]
52.2

**Comment by turbobabr** [comment]
You have to use the previous version of Duplicator:
https://github.com/turbobabr/duplicator/releases/download/v2.0.2/Duplicator.sketchplugin.zip

**Comment by zolotarsky** [comment]
Thank you for the answer!
