### ISSUE TITLE
Plugin not working with Sketch Beta v3.8

### ISSUE THREAD

**Issue by boomslam** [turbobabr/duplicator#9]
Some other plugins, like Runner, are broken too. If Sketch pushes an update and it starts working on its own I'll remove the issue.

**Comment by peiledoir** [comment]
Confirming the same issue with Duplicator (my most used plugin) :/

**Comment by turbobabr** [comment]
New version of Duplicator with 3.8 support is available:
https://github.com/turbobabr/duplicator/archive/duplicator-v1.1.zip

**Comment by peiledoir** [comment]
+100! Thank you
